[tool.poetry]
name = "movie_streaming-silletr"
version = "0.1.1"
description = "Python library with TUI & GUI for stream movie"
authors = ["Silletr <silletr@duck.com>"]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.7.3"
typer = "^0.21.1"

# [tool.poetry.scripts]
# pygit = "py_git.__main__:app"
cinemagoer = "^2023.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
